name: Set up Node.js and install packages
description: Set up Node.js with caching and install npm packages

inputs:
  node-version:
    description: Node.js version to use. If not specified, uses .node-version file
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        # If node-version and node-version-file are both provided the action will use version from node-version.
        node-version: ${{ inputs.node-version }}
        node-version-file: .node-version
        cache: npm

    - name: Install packages
      shell: bash
      run: npm ci
