name: Post commit status
description: Create or update a GitHub commit status using the Status API

inputs:
  state:
    description: Check run state (pending or outcome)
    required: true
  name:
    description: Check run name (e.g., "ci/build", "ci/lint", "ci/test")
    required: true
  job-status:
    description: 'Job status (for outcome checks; expected values: success, failure, cancelled, skipped)'
    required: false
  sha:
    description: Commit SHA to attach check run to
    required: true
  token:
    description: GitHub token with checks:write permission
    required: false

outputs:

runs:
  using: node24
  main: src/main.js
