name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to run against'
        required: false

permissions:
  contents: read # default to read-only access for repository contents

jobs:
  build:
    permissions:
      statuses: write # workflow_dispatch runs post commit status updates via gh api
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-and-set-nx-shas
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: ./.github/actions/post-status-check
        with:
          state: pending
          context: build

      - uses: ./.github/actions/setup-node-and-install

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t build

      - uses: ./.github/actions/post-status-check
        if: always()
        with:
          state: outcome
          context: build
          job-status: ${{ job.status }}

  lint:
    permissions:
      statuses: write # workflow_dispatch runs post commit status updates via gh api
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-and-set-nx-shas
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: ./.github/actions/post-status-check
        with:
          state: pending
          context: lint

      - uses: ./.github/actions/setup-node-and-install

      - name: '[PR] Check formatting'
        if: ${{ github.event_name == 'pull_request' }}
        run: npx nx format:check
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t lint

      - uses: ./.github/actions/post-status-check
        if: always()
        with:
          state: outcome
          context: lint
          job-status: ${{ job.status }}

  test:
    permissions:
      statuses: write # workflow_dispatch runs post commit status updates via gh api
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 18
          - os: ubuntu-latest
            node-version: 20
          - os: ubuntu-24.04-arm
            node-version: 22
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ./.github/actions/checkout-and-set-nx-shas
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: ./.github/actions/post-status-check
        with:
          state: pending
          context: test (${{ matrix.os }}, Node.js ${{ matrix.node-version }})

      - uses: ./.github/actions/setup-node-and-install
        with:
          node-version: ${{ matrix.node-version }}

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t test

      - uses: ./.github/actions/post-status-check
        if: always()
        with:
          state: outcome
          context: test (${{ matrix.os }}, Node.js ${{ matrix.node-version }})
          job-status: ${{ job.status }}

  e2e:
    permissions:
      statuses: write # workflow_dispatch runs post commit status updates via gh api
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - ubuntu-24.04-arm
          - windows-11-arm
          - macos-15-intel
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ./.github/actions/checkout-and-set-nx-shas
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: ./.github/actions/post-status-check
        with:
          state: pending
          context: e2e (${{ matrix.os }})

      - uses: ./.github/actions/setup-node-and-install

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t e2e

      - uses: ./.github/actions/post-status-check
        if: always()
        with:
          state: outcome
          context: e2e (${{ matrix.os }})
          job-status: ${{ job.status }}
