name: Weekly Dependency Update

on:
  schedule:
    # Every Monday at 03:00 UTC
    - cron: "0 3 * * 1"
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write # commit npm update changes, gh pr merge command
  pull-requests: write # peter-evans/create-pull-request action, gh pr merge command

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies to latest version compatible with version range
        run: npm update

      - name: Commit changes
        id: commit-changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet -- package.json package-lock.json; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
          else
            git add package.json package-lock.json
            git commit -m "chore: update dependencies to latest compatible versions"
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: ${{ steps.commit-changes.outputs.changes == 'true' }}
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/update-dependencies
          title: "chore: update dependencies to latest compatible versions"
          body: |
            This PR was automatically generated by the weekly dependency update workflow.
            It updates all dependencies to their latest compatible versions.
          commit-message: "chore: update dependencies to latest compatible versions"
          labels: dependencies
      - name: Enable Pull Request Automerge
        if: ${{ steps.commit-changes.outputs.changes == 'true' && steps.create-pull-request.outputs.pull-request-number }}
        run: gh pr merge --merge --auto "${{ steps.create-pull-request.outputs.pull-request-number }}"
