name: Dependency Update CI

on:
  workflow_run:
    workflows:
      - Weekly Dependency Update
    types:
      - completed

permissions:
  actions: write
  checks: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  detect-pr:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.find.outputs.number }}
      ref: ${{ steps.find.outputs.ref }}
    steps:
      - name: Locate dependency update PR
        id: find
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_json=$(gh pr list --repo "$GITHUB_REPOSITORY" --state open --head chore/update-dependencies --base main --json number,headRefName --limit 1)
          pr_number=$(echo "$pr_json" | jq -r '.[0].number // ""')
          pr_ref=$(echo "$pr_json" | jq -r '.[0].headRefName // ""')

          if [ -z "$pr_number" ] || [ "$pr_number" = "null" ]; then
            echo "number=" >> "$GITHUB_OUTPUT"
            echo "ref=" >> "$GITHUB_OUTPUT"
            echo "No dependency update pull request found; skipping." >&2
          else
            echo "number=$pr_number" >> "$GITHUB_OUTPUT"
            echo "ref=$pr_ref" >> "$GITHUB_OUTPUT"
            echo "Found dependency update pull request #$pr_number." >&2
          fi

  dispatch-ci:
    needs: detect-pr
    if: needs.detect-pr.outputs.number != ''
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: '${{ needs.detect-pr.outputs.ref }}',
              inputs: { ref: '${{ needs.detect-pr.outputs.ref }}' }
            });

  enable-automerge:
    needs:
      - detect-pr
      - dispatch-ci
    if: needs.detect-pr.outputs.number != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable PR automerge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ needs.detect-pr.outputs.number }} --merge --auto --repo "$GITHUB_REPOSITORY"
